# Generated by Django 5.2.8 on 2025-11-26 21:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_remove_payment_currency_payment_amount_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="amount_currency",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="fee_currency",
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="payment",
            name="fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
