# Generated by Django 5.2.7 on 2025-11-25 21:37

import affiliates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="referral_code",
            field=models.CharField(
                default=affiliates.models._generate_referral_code,
                max_length=32,
                unique=True,
            ),
        ),
    ]
