# Generated by Django 5.2.7 on 2025-11-27 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliates", "0002_alter_profile_referral_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commission",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddField(
            model_name="commission",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="commission",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="commission",
            name="source_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_commissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
