# Generated by Django 5.2.8 on 2025-12-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("affiliates", "0004_profile_referral_code_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="creator_monthly_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_creator",
            field=models.BooleanField(default=False),
        ),
    ]
