# Generated by Django 5.2.8 on 2025-12-06 20:08

from decimal import Decimal

from django.db import migrations, models


def create_default_commission_levels(apps, schema_editor):
    """Create default commission levels: 10%, 5%, 2% for levels 1, 2, 3"""
    CommissionLevel = apps.get_model("affiliates", "CommissionLevel")
    default_levels = [
        (1, Decimal("0.10")),  # 10%
        (2, Decimal("0.05")),  # 5%
        (3, Decimal("0.02")),  # 2%
    ]
    for level, rate in default_levels:
        CommissionLevel.objects.get_or_create(
            level=level,
            defaults={"rate": rate, "active": True},
        )


def remove_default_commission_levels(apps, schema_editor):
    """Remove default commission levels (reverse migration)"""
    CommissionLevel = apps.get_model("affiliates", "CommissionLevel")
    CommissionLevel.objects.filter(level__in=[1, 2, 3]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0005_profile_creator_monthly_price_profile_is_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(help_text="Commission level (1 = direct referrer, 2 = referrer's referrer, etc.)", unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Commission rate as a decimal (e.g., 0.10 for 10%)', max_digits=3)),
                ('active', models.BooleanField(default=True, help_text='Whether this level is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Level',
                'verbose_name_plural': 'Commission Levels',
                'ordering': ('level',),
            },
        ),
        migrations.RunPython(
            create_default_commission_levels,
            remove_default_commission_levels,
        ),
    ]
