# Generated by Django 5.2.7 on 2025-11-27 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0002_alter_creatorsubscription_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plan",
            options={"ordering": ("billing_period", "price")},
        ),
        migrations.AddField(
            model_name="plan",
            name="billing_period",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
